### ISSUE TITLE
The full Root tree is not displayed to a new user even when in Adminstrators group.

### ISSUE THREAD

**Issue by purplemana** [SenseNet/sensenet#424] opened 2018-07-24 12:03 UTC
A little background - https://github.com/SenseNet/sensenet/issues/423.

I created a new user and added it to `Administrators` group. When browsing the Explorer in remote using the new user's credentials, I still don't see the entire Root tree as it appears for `Admin` login. Especially missing is IMS. 

If I type `/Root/IMS` in the URL, IMS opens up empty. No `Builtin` domain, no roles, no users. I am able to create new domain and users in the UI though, but the builtins don't show. 

If I type `/Root/IMS/Builtin`, that also opens up empty, no users.

Is this expected?

**Comment by tusmester** [comment] 2018-08-01 15:05
This sounds strange and unfortunately we could not reproduce it. A new user added to the Administrators group should be able to see the portal the same way as the builtin admin, because that user is not a member of any other group, only the builtin admins group - so the two admin users should have the same permissions.

**Comment by tusmester** [comment] 2018-08-22 09:33
We are closing this as not reproducible, likely to be caused by an index anomaly. If you can still reproduce this or have more info, please let us know.

**Closed by tusmester** 2018-08-22 09:33 UTC
Labels: question
